# -*- coding: utf-8 -*-
"""1122演算法.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEK2WSBjfFxFX3UgmZinrFeNEL9YiabD
"""

import time
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

def fibo_DC(n):
    if n < 2:
        return n
    else:
        return fibo_DC(n - 1) + fibo_DC(n - 2)

def fibo_DP(n):
    if n < 0:
        print("Invalid number")
        return

    fibo = [1, 1]
    for i in range(n):
        if i <= 1:
            continue
        else:
            fibo.append(fibo[-1] + fibo[-2])

    return fibo[-1]

n1 = list(range(41))
DC = [None] * len(n1)
DP = [None] * len(n1)
dat1 = pd.DataFrame({"n1": n1, "DC": DC, "DP": DP})
dat1

for i in n1:
    start_time1 = time.time()
    fibo_DC(i)
    end_time1 = time.time()

    start_time2 = time.time()
    fibo_DP(i)
    end_time2 = time.time()

    dat1.at[i, "DC"] = end_time1 - start_time1
    dat1.at[i, "DP"] = end_time2 - start_time2

dat1

dat1.to_csv('algo_HW1.csv', encoding = 'utf-8-sig')
files.download('algo_HW1.csv')

plt.plot(dat1["n1"], dat1["DC"], 'ro-')
plt.plot(dat1["n1"], dat1["DP"], 'go-')
plt.show()

#calculate the times of F(4) in fibo_seq using DC
def fibo_DC_count4(n):
  count4 = 0
  if n<4:
    return 0
  elif n==4:
    return 1
  else:
    return fibo_DC_count4(n-1)+fibo_DC_count4(n-2)

#calculate the times of F(4) in fibo_seq using DP
def fibo_DP_count4(n):
  fibo = [0, 1]
  count4 = 0
  if n<2:
    return n, count4

  for i in range(2, n+1):
    fibo.append(fibo[i-1]+fibo[i-2])
    if i==4:
      count4 +=1

  return fibo[n], count4

n2 = list(range(5, 51))
DC = [None] * len(n2)
DP = [None] * len(n2)
dat2 = pd.DataFrame({"n2": n2, "DC": DC, "DP": DP})
dat2

for i in range(len(n2)):
  dat2.at[i, "DC"] = fibo_DC_count4(n2[i])
  dat2.at[i, "DP"] = fibo_DP_count4(n2[i])[1]

dat2

dat2.to_csv('algo_HW2.csv', encoding = 'utf-8-sig')
files.download('algo_HW2.csv')

plt.plot(dat2["n2"], dat2["DC"], 'ro-')
plt.plot(dat2["n2"], dat2["DP"], 'go-')
plt.show()